In [3]:
%pip install spotipy
%pip install python-dotenv

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: spotipy in /Users/gauravambasta/Library/Python/3.9/lib/python/site-packages (2.26.0)
Requirement already satisfied: redis>=3.5.3 in /Users/gauravambasta/Library/Python/3.9/lib/python/site-packages (from spotipy) (7.0.1)
Requirement already satisfied: requests>=2.25.0 in /Users/gauravambasta/Library/Python/3.9/lib/python/site-packages (from spotipy) (2.32.5)
Requirement already satisfied: urllib3>=1.26.0 in /Users/gauravambasta/Library/Python/3.9/lib/python/site-packages (from spotipy) (2.6.3)
Requirement already satisfied: async-timeout>=4.0.3 in /Users/gauravambasta/Library/Python/3.9/lib/python/site-packages (from redis>=3.5.3->spotipy) (5.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/gauravambasta/Library/Python/3.9/lib/python/site-packages (from requests>=2.25.0->spotipy) (2026.7.22)
Requirement already satisfied: idna<4,>=2.5 in /Users/gauravambasta/Library/Python/3.9/lib/python/site-packages (from requests>=2.25.0->spotipy) (3.18)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/gauravambasta/Library/Python/3.9/lib/python/site-packages (from requests>=2.25.0->spotipy) (3.5.1)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dotenv in /Users/gauravambasta/Library/Python/3.9/lib/python/site-packages (1.2.1)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [4]:
import os
from dotenv import load_dotenv

load_dotenv()

client_id = os.getenv("SPOTIFY_CLIENT_ID")
client_secret = os.getenv("SPOTIFY_CLIENT_SECRET")

In [5]:
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import pandas as pd

In [6]:
sp = spotipy.Spotify(
    auth_manager=SpotifyOAuth(
        client_id=client_id,
        client_secret=client_secret,
        redirect_uri="http://127.0.0.1:8889/callback",
        scope="playlist-read-private"
    )
)

In [7]:
token_info = sp.auth_manager.get_cached_token()
print(token_info.keys() if token_info else "No cached token found")

dict_keys(['access_token', 'token_type', 'expires_in', 'scope', 'expires_at', 'refresh_token'])

In [37]:
refresh_token = token_info['refresh_token']
print(refresh_token is not None)
print(refresh_token)

True
AQDofFfMjXjNWFaZS6BYj7tcNcIfjx8oxQaNpGCqo6OH5bTNN6wxhFluyqaXjpA9Y7fd3zojn9wmIcXDYyfRHD79Ddia_PEQLtvC_M_snzq3DRDULbOtXEkO2Rvx52MYNGY

In [8]:
playlist_link = "https://open.spotify.com/playlist/0kg3Niymj7CG4ArhD6lN7W"

In [9]:
playlist_URI = playlist_link.split("/")[-1]

In [10]:
data = sp.playlist_items(playlist_URI)
data['items'][0]['item']

{'is_playable': True,
 'explicit': False,
 'type': 'track',
 'episode': False,
 'track': True,
 'album': {'is_playable': True,
  'type': 'album',
  'album_type': 'album',
  'href': 'https://api.spotify.com/v1/albums/13t8iDyl1vkhPcO3Zl29a9',
  'id': '13t8iDyl1vkhPcO3Zl29a9',
  'images': [{'height': 640,
    'url': 'https://i.scdn.co/image/ab67616d0000b273d7f366eb7dff75c47a6cd604',
    'width': 640},
   {'height': 300,
    'url': 'https://i.scdn.co/image/ab67616d00001e02d7f366eb7dff75c47a6cd604',
    'width': 300},
   {'height': 64,
    'url': 'https://i.scdn.co/image/ab67616d00004851d7f366eb7dff75c47a6cd604',
    'width': 64}],
  'name': 'Ajab Prem Ki Ghazab Kahani (Original Motion Picture Soundtrack)',
  'release_date': '2009-11-06',
  'release_date_precision': 'day',
  'uri': 'spotify:album:13t8iDyl1vkhPcO3Zl29a9',
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1wRPtKGflJrBx9BmLsSwlU'},
    'href': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU',
    'id': '1wRPtKGflJrBx9BmLsSwlU',
    'name': 'Pritam',
    'type': 'artist',
    'uri': 'spotify:artist:1wRPtKGflJrBx9BmLsSwlU'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/3GdSQUH1BRtl9UrrtuwJlP'},
    'href': 'https://api.spotify.com/v1/artists/3GdSQUH1BRtl9UrrtuwJlP',
    'id': '3GdSQUH1BRtl9UrrtuwJlP',
    'name': 'Irshad Kamil',
    'type': 'artist',
    'uri': 'spotify:artist:3GdSQUH1BRtl9UrrtuwJlP'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/1Xoow41U5fn5DwlMlYt7Gw'},
    'href': 'https://api.spotify.com/v1/artists/1Xoow41U5fn5DwlMlYt7Gw',
    'id': '1Xoow41U5fn5DwlMlYt7Gw',
    'name': 'Hard Kaur',
    'type': 'artist',
    'uri': 'spotify:artist:1Xoow41U5fn5DwlMlYt7Gw'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/03veJpSIc7GAx0mPLcskjI'},
    'href': 'https://api.spotify.com/v1/artists/03veJpSIc7GAx0mPLcskjI',
    'id': '03veJpSIc7GAx0mPLcskjI',
    'name': 'Ashish Pandit',
    'type': 'artist',
    'uri': 'spotify:artist:03veJpSIc7GAx0mPLcskjI'}],
  'external_urls': {'spotify': 'https://open.spotify.com/album/13t8iDyl1vkhPcO3Zl29a9'},
  'total_tracks': 14},
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1wRPtKGflJrBx9BmLsSwlU'},
   'href': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU',
   'id': '1wRPtKGflJrBx9BmLsSwlU',
   'name': 'Pritam',
   'type': 'artist',
   'uri': 'spotify:artist:1wRPtKGflJrBx9BmLsSwlU'},
  {'external_urls': {'spotify': 'https://open.spotify.com/artist/2oSONSC9zQ4UonDKnLqksx'},
   'href': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx',
   'id': '2oSONSC9zQ4UonDKnLqksx',
   'name': 'Atif Aslam',
   'type': 'artist',
   'uri': 'spotify:artist:2oSONSC9zQ4UonDKnLqksx'},
  {'external_urls': {'spotify': 'https://open.spotify.com/artist/4mBxoO0pAcMbAwuTcrcLMc'},
   'href': 'https://api.spotify.com/v1/artists/4mBxoO0pAcMbAwuTcrcLMc',
   'id': '4mBxoO0pAcMbAwuTcrcLMc',
   'name': 'Alisha Chinai',
   'type': 'artist',
   'uri': 'spotify:artist:4mBxoO0pAcMbAwuTcrcLMc'}],
 'disc_number': 1,
 'track_number': 9,
 'duration_ms': 299827,
 'external_ids': {'isrc': 'INT100900021'},
 'external_urls': {'spotify': 'https://open.spotify.com/track/0dLbrlAVPPjpPqnYfmJsWk'},
 'href': 'https://api.spotify.com/v1/tracks/0dLbrlAVPPjpPqnYfmJsWk',
 'id': '0dLbrlAVPPjpPqnYfmJsWk',
 'name': 'Tera Hone Laga Hoon',
 'uri': 'spotify:track:0dLbrlAVPPjpPqnYfmJsWk',
 'is_local': False}

In [11]:
data['items'][0]['item']['album']['id']

'13t8iDyl1vkhPcO3Zl29a9'

In [12]:
data['items'][0]['item']['album']['name']

'Ajab Prem Ki Ghazab Kahani (Original Motion Picture Soundtrack)'

In [13]:
data['items'][0]['item']['album']['release_date']

'2009-11-06'

In [14]:
data['items'][0]['item']['album']['total_tracks']

14

In [15]:
data['items'][0]['item']['album']['external_urls']['spotify']

'https://open.spotify.com/album/13t8iDyl1vkhPcO3Zl29a9'

In [16]:
album_list =[]
for row in data['items']:

    album_id = row ['item']['album']['id']
    album_name = row ['item']['album']['name']
    album_release_date = row ['item']['album']['release_date']
    # print(release_date)
    album_total_tracks = row ['item']['album']['total_tracks']
    album_url = row ['item']['album']['external_urls']['spotify']
    # print(album_url)

    album_element = {'album_id': album_id, 'album_name': album_name, 'release_date': album_release_date, 'total_tracks': album_total_tracks, 'url': album_url}

    album_list.append(album_element)

In [17]:
data['items'][0]['item']['artists']

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1wRPtKGflJrBx9BmLsSwlU'},
  'href': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU',
  'id': '1wRPtKGflJrBx9BmLsSwlU',
  'name': 'Pritam',
  'type': 'artist',
  'uri': 'spotify:artist:1wRPtKGflJrBx9BmLsSwlU'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/2oSONSC9zQ4UonDKnLqksx'},
  'href': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx',
  'id': '2oSONSC9zQ4UonDKnLqksx',
  'name': 'Atif Aslam',
  'type': 'artist',
  'uri': 'spotify:artist:2oSONSC9zQ4UonDKnLqksx'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/4mBxoO0pAcMbAwuTcrcLMc'},
  'href': 'https://api.spotify.com/v1/artists/4mBxoO0pAcMbAwuTcrcLMc',
  'id': '4mBxoO0pAcMbAwuTcrcLMc',
  'name': 'Alisha Chinai',
  'type': 'artist',
  'uri': 'spotify:artist:4mBxoO0pAcMbAwuTcrcLMc'}]

In [18]:
artist_list = []

for row in data['items']:
    for key, value in row.items():
        if key == "item":
            for artist in value['artists']:
                artist_dict = {
                    'artist_id': artist['id'],
                    'artist_name': artist['name'],
                    'external_url': artist['href']
                }

                artist_list.append(artist_dict)

In [19]:
print(artist_list)

[{'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '2oSONSC9zQ4UonDKnLqksx', 'artist_name': 'Atif Aslam', 'external_url': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx'}, {'artist_id': '4mBxoO0pAcMbAwuTcrcLMc', 'artist_name': 'Alisha Chinai', 'external_url': 'https://api.spotify.com/v1/artists/4mBxoO0pAcMbAwuTcrcLMc'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '5GnnSrwNCGyfAU4zuIytiS', 'artist_name': 'Mohit Chauhan', 'external_url': 'https://api.spotify.com/v1/artists/5GnnSrwNCGyfAU4zuIytiS'}, {'artist_id': '3GdSQUH1BRtl9UrrtuwJlP', 'artist_name': 'Irshad Kamil', 'external_url': 'https://api.spotify.com/v1/artists/3GdSQUH1BRtl9UrrtuwJlP'}, {'artist_id': '1mBydYMVBECdDmMfE2sEUO', 'artist_name': 'Sachin-Jigar', 'external_url': 'https://api.spotify.com/v1/artists/1mBydYMVBECdDmMfE2sEUO'}, {'artist_id': '2oSONSC9zQ4UonDKnLqksx', 'artist_name': 'Atif Aslam', 'external_url': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '64j5rJTsD25fTAcOiZWAiY', 'artist_name': 'Samyak Prasana', 'external_url': 'https://api.spotify.com/v1/artists/64j5rJTsD25fTAcOiZWAiY'}, {'artist_id': '1FWl7I9wJpb7Bhhutef4Xe', 'artist_name': 'Taaruk Raina', 'external_url': 'https://api.spotify.com/v1/artists/1FWl7I9wJpb7Bhhutef4Xe'}, {'artist_id': '0NbgKDsEHiPzZBZkqZGkXm', 'artist_name': 'Mismatched - Cast', 'external_url': 'https://api.spotify.com/v1/artists/0NbgKDsEHiPzZBZkqZGkXm'}, {'artist_id': '5GnnSrwNCGyfAU4zuIytiS', 'artist_name': 'Mohit Chauhan', 'external_url': 'https://api.spotify.com/v1/artists/5GnnSrwNCGyfAU4zuIytiS'}, {'artist_id': '4HQeSXwG2BVH0KvxHE5oCf', 'artist_name': "Suzanne D'Mello", 'external_url': 'https://api.spotify.com/v1/artists/4HQeSXwG2BVH0KvxHE5oCf'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '3yMmYEklQ7gLOZXEFNd3xr', 'artist_name': 'Palak Muchhal', 'external_url': 'https://api.spotify.com/v1/artists/3yMmYEklQ7gLOZXEFNd3xr'}, {'artist_id': '4cAERazLlAzVGA10ORWaUP', 'artist_name': 'Manoj Muntashir', 'external_url': 'https://api.spotify.com/v1/artists/4cAERazLlAzVGA10ORWaUP'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '1cfG7UM0OD4O1II1nd15Qo', 'artist_name': 'Ash King', 'external_url': 'https://api.spotify.com/v1/artists/1cfG7UM0OD4O1II1nd15Qo'}, {'artist_id': '3eDT9fwXKuHWFvgZaaYC5v', 'artist_name': 'Sunidhi Chauhan', 'external_url': 'https://api.spotify.com/v1/artists/3eDT9fwXKuHWFvgZaaYC5v'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '4fEkbug6kZzzJ8eYX6Kbbp', 'artist_name': 'KK', 'external_url': 'https://api.spotify.com/v1/artists/4fEkbug6kZzzJ8eYX6Kbbp'}, {'artist_id': '2pGRniGOJSOvYoK3dGaBb8', 'artist_name': 'Sayeed Quadri', 'external_url': 'https://api.spotify.com/v1/artists/2pGRniGOJSOvYoK3dGaBb8'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '3yMmYEklQ7gLOZXEFNd3xr', 'artist_name': 'Palak Muchhal', 'external_url': 'https://api.spotify.com/v1/artists/3yMmYEklQ7gLOZXEFNd3xr'}, {'artist_id': '2zvJLk0gTH7r7A5Q6X5Bq8', 'artist_name': 'Javed-Mohsin', 'external_url': 'https://api.spotify.com/v1/artists/2zvJLk0gTH7r7A5Q6X5Bq8'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '52XgeWw24o4klNdfwvB0Vx', 'artist_name': 'Kunaal Vermaa', 'external_url': 'https://api.spotify.com/v1/artists/52XgeWw24o4klNdfwvB0Vx'}, {'artist_id': '5DNHuR9u8DFVasxQZgREO5', 'artist_name': 'Prashant Ingole', 'external_url': 'https://api.spotify.com/v1/artists/5DNHuR9u8DFVasxQZgREO5'}, {'artist_id': '1bTROl5p3rGTpvKeWnGgrw', 'artist_name': 'Sohail Sen', 'external_url': 'https://api.spotify.com/v1/artists/1bTROl5p3rGTpvKeWnGgrw'}, {'artist_id': '5GnnSrwNCGyfAU4zuIytiS', 'artist_name': 'Mohit Chauhan', 'external_url': 'https://api.spotify.com/v1/artists/5GnnSrwNCGyfAU4zuIytiS'}, {'artist_id': '3dihrcurT9YFHMT8KpaIKa', 'artist_name': 'Tarannum Malik Jain', 'external_url': 'https://api.spotify.com/v1/artists/3dihrcurT9YFHMT8KpaIKa'}, {'artist_id': '3GBSge8pq7mpezUQl0GAOA', 'artist_name': 'Kausar Munir', 'external_url': 'https://api.spotify.com/v1/artists/3GBSge8pq7mpezUQl0GAOA'}, {'artist_id': '2oSONSC9zQ4UonDKnLqksx', 'artist_name': 'Atif Aslam', 'external_url': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx'}, {'artist_id': '5ugsiK49gIkIVh8U93EO0z', 'artist_name': 'Ami Mishra', 'external_url': 'https://api.spotify.com/v1/artists/5ugsiK49gIkIVh8U93EO0z'}, {'artist_id': '52XgeWw24o4klNdfwvB0Vx', 'artist_name': 'Kunaal Vermaa', 'external_url': 'https://api.spotify.com/v1/artists/52XgeWw24o4klNdfwvB0Vx'}, {'artist_id': '2oSONSC9zQ4UonDKnLqksx', 'artist_name': 'Atif Aslam', 'external_url': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx'}, {'artist_id': '6jf2eKjiPT6P18RbOSLzf0', 'artist_name': 'Arko', 'external_url': 'https://api.spotify.com/v1/artists/6jf2eKjiPT6P18RbOSLzf0'}, {'artist_id': '2oSONSC9zQ4UonDKnLqksx', 'artist_name': 'Atif Aslam', 'external_url': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx'}, {'artist_id': '7DcUua74PM7MmBljTTjIyy', 'artist_name': 'Shiraz Uppal', 'external_url': 'https://api.spotify.com/v1/artists/7DcUua74PM7MmBljTTjIyy'}, {'artist_id': '50tVmZsA8fsA1Bo5VUcOcA', 'artist_name': 'Shakeel Sohail', 'external_url': 'https://api.spotify.com/v1/artists/50tVmZsA8fsA1Bo5VUcOcA'}, {'artist_id': '1yzgJmZf5CxtFfGfRFm4Si', 'artist_name': 'Gajendra Verma', 'external_url': 'https://api.spotify.com/v1/artists/1yzgJmZf5CxtFfGfRFm4Si'}, {'artist_id': '4IKVDbCSBTxBeAsMKjAuTs', 'artist_name': 'Armaan Malik', 'external_url': 'https://api.spotify.com/v1/artists/4IKVDbCSBTxBeAsMKjAuTs'}, {'artist_id': '5wJ1H6ud777odtZl5gG507', 'artist_name': 'Vishal Mishra', 'external_url': 'https://api.spotify.com/v1/artists/5wJ1H6ud777odtZl5gG507'}, {'artist_id': '3GdSQUH1BRtl9UrrtuwJlP', 'artist_name': 'Irshad Kamil', 'external_url': 'https://api.spotify.com/v1/artists/3GdSQUH1BRtl9UrrtuwJlP'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '2UwDJeoMqYers5Jmm75zm2', 'artist_name': 'Antara Mitra', 'external_url': 'https://api.spotify.com/v1/artists/2UwDJeoMqYers5Jmm75zm2'}, {'artist_id': '0qSfAhYhb7KWEuiLuooBaE', 'artist_name': 'Manoj Yadav', 'external_url': 'https://api.spotify.com/v1/artists/0qSfAhYhb7KWEuiLuooBaE'}, {'artist_id': '3TOhzLRYnkkul71yRBxIoM', 'artist_name': 'Akhil Sachdeva', 'external_url': 'https://api.spotify.com/v1/artists/3TOhzLRYnkkul71yRBxIoM'}, {'artist_id': '0T1CMVkqffHlqEk4BcAph1', 'artist_name': 'Tulsi Kumar', 'external_url': 'https://api.spotify.com/v1/artists/0T1CMVkqffHlqEk4BcAph1'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '6Mv8GjQa7LKUGCAqa9qqdb', 'artist_name': 'Vishal-Shekhar', 'external_url': 'https://api.spotify.com/v1/artists/6Mv8GjQa7LKUGCAqa9qqdb'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '5bv6NvAYNuvd2Vq13nHdG3', 'artist_name': 'Sona Mohapatra', 'external_url': 'https://api.spotify.com/v1/artists/5bv6NvAYNuvd2Vq13nHdG3'}, {'artist_id': '7HCqGPJcQTyGJ2yqntbuyr', 'artist_name': 'Amit Trivedi', 'external_url': 'https://api.spotify.com/v1/artists/7HCqGPJcQTyGJ2yqntbuyr'}, {'artist_id': '2fMqTqiTxUDlmcOEPaQSsx', 'artist_name': 'Amitabh Bhattacharya', 'external_url': 'https://api.spotify.com/v1/artists/2fMqTqiTxUDlmcOEPaQSsx'}, {'artist_id': '3ZiBHBeZ3OAKJEkDWzQFHS', 'artist_name': 'Sireesha Bhagavatula', 'external_url': 'https://api.spotify.com/v1/artists/3ZiBHBeZ3OAKJEkDWzQFHS'}, {'artist_id': '5OTt6O4Q22YsqZDaWV6FqC', 'artist_name': 'Bombay Jayashri', 'external_url': 'https://api.spotify.com/v1/artists/5OTt6O4Q22YsqZDaWV6FqC'}, {'artist_id': '4f7KfxeHq9BiylGmyXepGt', 'artist_name': 'Tanishk Bagchi', 'external_url': 'https://api.spotify.com/v1/artists/4f7KfxeHq9BiylGmyXepGt'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '1sVmXkzX2ukc6QvasrDBES', 'artist_name': 'Asees Kaur', 'external_url': 'https://api.spotify.com/v1/artists/1sVmXkzX2ukc6QvasrDBES'}, {'artist_id': '09UmIX92EUH9hAK4bxvHx6', 'artist_name': 'Mithoon', 'external_url': 'https://api.spotify.com/v1/artists/09UmIX92EUH9hAK4bxvHx6'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '3eDT9fwXKuHWFvgZaaYC5v', 'artist_name': 'Sunidhi Chauhan', 'external_url': 'https://api.spotify.com/v1/artists/3eDT9fwXKuHWFvgZaaYC5v'}, {'artist_id': '2pGRniGOJSOvYoK3dGaBb8', 'artist_name': 'Sayeed Quadri', 'external_url': 'https://api.spotify.com/v1/artists/2pGRniGOJSOvYoK3dGaBb8'}, {'artist_id': '6QtJ6BVdj43aDpgjnVp2tY', 'artist_name': 'Mohammed Irfan', 'external_url': 'https://api.spotify.com/v1/artists/6QtJ6BVdj43aDpgjnVp2tY'}, {'artist_id': '1yzgJmZf5CxtFfGfRFm4Si', 'artist_name': 'Gajendra Verma', 'external_url': 'https://api.spotify.com/v1/artists/1yzgJmZf5CxtFfGfRFm4Si'}, {'artist_id': '09UmIX92EUH9hAK4bxvHx6', 'artist_name': 'Mithoon', 'external_url': 'https://api.spotify.com/v1/artists/09UmIX92EUH9hAK4bxvHx6'}, {'artist_id': '6Mv8GjQa7LKUGCAqa9qqdb', 'artist_name': 'Vishal-Shekhar', 'external_url': 'https://api.spotify.com/v1/artists/6Mv8GjQa7LKUGCAqa9qqdb'}, {'artist_id': '5GnnSrwNCGyfAU4zuIytiS', 'artist_name': 'Mohit Chauhan', 'external_url': 'https://api.spotify.com/v1/artists/5GnnSrwNCGyfAU4zuIytiS'}, {'artist_id': '4xd7mLI7urqrxELaXhAvzw', 'artist_name': 'Shekhar Ravjiani', 'external_url': 'https://api.spotify.com/v1/artists/4xd7mLI7urqrxELaXhAvzw'}, {'artist_id': '3wZBspj86lRk2XLf4gfnSE', 'artist_name': 'Shruti Pathak', 'external_url': 'https://api.spotify.com/v1/artists/3wZBspj86lRk2XLf4gfnSE'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '5SuRAj1A9FEHj5NxS86YAm', 'artist_name': 'Shafqat Amanat Ali', 'external_url': 'https://api.spotify.com/v1/artists/5SuRAj1A9FEHj5NxS86YAm'}, {'artist_id': '2pGRniGOJSOvYoK3dGaBb8', 'artist_name': 'Sayeed Quadri', 'external_url': 'https://api.spotify.com/v1/artists/2pGRniGOJSOvYoK3dGaBb8'}, {'artist_id': '0sSxphmGskGCKlwB9xa6WU', 'artist_name': 'Himesh Reshammiya', 'external_url': 'https://api.spotify.com/v1/artists/0sSxphmGskGCKlwB9xa6WU'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '0T1CMVkqffHlqEk4BcAph1', 'artist_name': 'Tulsi Kumar', 'external_url': 'https://api.spotify.com/v1/artists/0T1CMVkqffHlqEk4BcAph1'}, {'artist_id': '2oSONSC9zQ4UonDKnLqksx', 'artist_name': 'Atif Aslam', 'external_url': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx'}, {'artist_id': '3dN9MQpjIyNxyeRfz4EDZe', 'artist_name': 'Rochak Kohli', 'external_url': 'https://api.spotify.com/v1/artists/3dN9MQpjIyNxyeRfz4EDZe'}, {'artist_id': '0m3D4grap8VFSzbJMqgNVk', 'artist_name': 'Kumaar', 'external_url': 'https://api.spotify.com/v1/artists/0m3D4grap8VFSzbJMqgNVk'}, {'artist_id': '6CXEwIaXYfVJ84biCxqc9k', 'artist_name': 'Vishal Dadlani', 'external_url': 'https://api.spotify.com/v1/artists/6CXEwIaXYfVJ84biCxqc9k'}, {'artist_id': '3PpjqSKBer3obW6lDflOBx', 'artist_name': 'Ram Sampath', 'external_url': 'https://api.spotify.com/v1/artists/3PpjqSKBer3obW6lDflOBx'}, {'artist_id': '3UpmjPgIFSGqnxXuiwD014', 'artist_name': 'Javed Akhtar', 'external_url': 'https://api.spotify.com/v1/artists/3UpmjPgIFSGqnxXuiwD014'}, {'artist_id': '56SjZARoEvag3RoKWIb16j', 'artist_name': 'B Praak', 'external_url': 'https://api.spotify.com/v1/artists/56SjZARoEvag3RoKWIb16j'}, {'artist_id': '5gZhfbckaWo89OzDSk3gdT', 'artist_name': 'Jaani', 'external_url': 'https://api.spotify.com/v1/artists/5gZhfbckaWo89OzDSk3gdT'}, {'artist_id': '4fEkbug6kZzzJ8eYX6Kbbp', 'artist_name': 'KK', 'external_url': 'https://api.spotify.com/v1/artists/4fEkbug6kZzzJ8eYX6Kbbp'}, {'artist_id': '1mBydYMVBECdDmMfE2sEUO', 'artist_name': 'Sachin-Jigar', 'external_url': 'https://api.spotify.com/v1/artists/1mBydYMVBECdDmMfE2sEUO'}, {'artist_id': '2oSONSC9zQ4UonDKnLqksx', 'artist_name': 'Atif Aslam', 'external_url': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '71oGOxg5ez52Hh1Ye41A98', 'artist_name': 'Mustafa Zahid', 'external_url': 'https://api.spotify.com/v1/artists/71oGOxg5ez52Hh1Ye41A98'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '2bfyLSCw72lQ5qoD8cdVBB', 'artist_name': 'Sreerama Chandra', 'external_url': 'https://api.spotify.com/v1/artists/2bfyLSCw72lQ5qoD8cdVBB'}, {'artist_id': '19LIHDDSHBD5NyYHI3gpzB', 'artist_name': 'Shilpa Rao', 'external_url': 'https://api.spotify.com/v1/artists/19LIHDDSHBD5NyYHI3gpzB'}, {'artist_id': '2fMqTqiTxUDlmcOEPaQSsx', 'artist_name': 'Amitabh Bhattacharya', 'external_url': 'https://api.spotify.com/v1/artists/2fMqTqiTxUDlmcOEPaQSsx'}, {'artist_id': '1mYsTxnqsietFxj1OgoGbG', 'artist_name': 'A.R. Rahman', 'external_url': 'https://api.spotify.com/v1/artists/1mYsTxnqsietFxj1OgoGbG'}, {'artist_id': '4rD8zSLMVjpdgJyW14Lokh', 'artist_name': 'Rabbi', 'external_url': 'https://api.spotify.com/v1/artists/4rD8zSLMVjpdgJyW14Lokh'}, {'artist_id': '0yRC5n90spXG0d3aiDQ0vB', 'artist_name': 'Gulzar', 'external_url': 'https://api.spotify.com/v1/artists/0yRC5n90spXG0d3aiDQ0vB'}, {'artist_id': '3ILK3wZ5nqQr7O79aF8G53', 'artist_name': 'Yashal Shahid', 'external_url': 'https://api.spotify.com/v1/artists/3ILK3wZ5nqQr7O79aF8G53'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '5GnnSrwNCGyfAU4zuIytiS', 'artist_name': 'Mohit Chauhan', 'external_url': 'https://api.spotify.com/v1/artists/5GnnSrwNCGyfAU4zuIytiS'}, {'artist_id': '7qATomOqJzoJiuEpAaxOXd', 'artist_name': 'Sandeep Shrivastava', 'external_url': 'https://api.spotify.com/v1/artists/7qATomOqJzoJiuEpAaxOXd'}, {'artist_id': '4IKVDbCSBTxBeAsMKjAuTs', 'artist_name': 'Armaan Malik', 'external_url': 'https://api.spotify.com/v1/artists/4IKVDbCSBTxBeAsMKjAuTs'}, {'artist_id': '76fuWYgIf3TVIopTs3vaJ6', 'artist_name': 'Amaal Mallik', 'external_url': 'https://api.spotify.com/v1/artists/76fuWYgIf3TVIopTs3vaJ6'}, {'artist_id': '4cAERazLlAzVGA10ORWaUP', 'artist_name': 'Manoj Muntashir', 'external_url': 'https://api.spotify.com/v1/artists/4cAERazLlAzVGA10ORWaUP'}, {'artist_id': '2oSONSC9zQ4UonDKnLqksx', 'artist_name': 'Atif Aslam', 'external_url': 'https://api.spotify.com/v1/artists/2oSONSC9zQ4UonDKnLqksx'}, {'artist_id': '5HcunTidTUrOaf8V0iJcvl', 'artist_name': 'Nusrat Fateh Ali Khan', 'external_url': 'https://api.spotify.com/v1/artists/5HcunTidTUrOaf8V0iJcvl'}, {'artist_id': '3dN9MQpjIyNxyeRfz4EDZe', 'artist_name': 'Rochak Kohli', 'external_url': 'https://api.spotify.com/v1/artists/3dN9MQpjIyNxyeRfz4EDZe'}, {'artist_id': '4cAERazLlAzVGA10ORWaUP', 'artist_name': 'Manoj Muntashir', 'external_url': 'https://api.spotify.com/v1/artists/4cAERazLlAzVGA10ORWaUP'}, {'artist_id': '71oGOxg5ez52Hh1Ye41A98', 'artist_name': 'Mustafa Zahid', 'external_url': 'https://api.spotify.com/v1/artists/71oGOxg5ez52Hh1Ye41A98'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '5cB4d4jPYjMT326sjihQ4m', 'artist_name': 'Shaan', 'external_url': 'https://api.spotify.com/v1/artists/5cB4d4jPYjMT326sjihQ4m'}, {'artist_id': '2eOZNXw0A4cQKmsVPpIcMY', 'artist_name': 'Ustad Sultan Khan', 'external_url': 'https://api.spotify.com/v1/artists/2eOZNXw0A4cQKmsVPpIcMY'}, {'artist_id': '3GdSQUH1BRtl9UrrtuwJlP', 'artist_name': 'Irshad Kamil', 'external_url': 'https://api.spotify.com/v1/artists/3GdSQUH1BRtl9UrrtuwJlP'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '2fMqTqiTxUDlmcOEPaQSsx', 'artist_name': 'Amitabh Bhattacharya', 'external_url': 'https://api.spotify.com/v1/artists/2fMqTqiTxUDlmcOEPaQSsx'}, {'artist_id': '6QtJ6BVdj43aDpgjnVp2tY', 'artist_name': 'Mohammed Irfan', 'external_url': 'https://api.spotify.com/v1/artists/6QtJ6BVdj43aDpgjnVp2tY'}, {'artist_id': '2GoeZ0qOTt6kjsWW4eA6LS', 'artist_name': 'Darshan Raval', 'external_url': 'https://api.spotify.com/v1/artists/2GoeZ0qOTt6kjsWW4eA6LS'}, {'artist_id': '0qpsFfOT3SmdGmnyV6rOhS', 'artist_name': 'Meet Bros.', 'external_url': 'https://api.spotify.com/v1/artists/0qpsFfOT3SmdGmnyV6rOhS'}, {'artist_id': '4YRxDV8wJFPHPTeXepOstw', 'artist_name': 'Arijit Singh', 'external_url': 'https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '1wRPtKGflJrBx9BmLsSwlU', 'artist_name': 'Pritam', 'external_url': 'https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU'}, {'artist_id': '4fEkbug6kZzzJ8eYX6Kbbp', 'artist_name': 'KK', 'external_url': 'https://api.spotify.com/v1/artists/4fEkbug6kZzzJ8eYX6Kbbp'}, {'artist_id': '1XUGerdrjDBJxF9ZfxMqDj', 'artist_name': 'Mayur Puri', 'external_url': 'https://api.spotify.com/v1/artists/1XUGerdrjDBJxF9ZfxMqDj'}]

In [20]:
song_list = []

for row in data['items']:
    song = row['item']

    song_element = {
        'song_id': song['id'],
        'song_name': song['name'],
        'duration_ms': song['duration_ms'],
        'url': song['external_urls']['spotify'],
        'song_added': row['added_at'],
        'album_id': song['album']['id'],
        'artist_id': song['artists'][0]['id']
    }

    song_list.append(song_element)

In [21]:
album_df = pd.DataFrame.from_dict(album_list)

In [22]:
album_df.head()

,album_id,album_name,release_date,total_tracks,url
0,13t8iDyl1vkhPcO3Zl29a9,Ajab Prem Ki Ghazab Kahani (Original Motion Pi...,2009-11-06,14,https://open.spotify.com/album/13t8iDyl1vkhPcO...
1,2yoQE2XBnwdUyoOkoprTfT,Love Aaj Kal (Original Motion Picture Soundtrack),2009-07-31,10,https://open.spotify.com/album/2yoQE2XBnwdUyoO...
2,0OhM0xKiFdqKakSWYx0hs4,Tere Naal Love Ho Gaya (Original Motion Pictur...,2011-02-24,12,https://open.spotify.com/album/0OhM0xKiFdqKakS...
3,5rxVfBCI8RvZzTmnLyXQ97,Aahatein (unplugged),2022-08-14,1,https://open.spotify.com/album/5rxVfBCI8RvZzTm...
4,0bPV8j4jfsKeoW5P3YQInX,Mismatched: Season 2 (Soundtrack from the Netf...,2022-09-30,9,https://open.spotify.com/album/0bPV8j4jfsKeoW5...

In [23]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      50 non-null     object
 1   album_name    50 non-null     object
 2   release_date  50 non-null     object
 3   total_tracks  50 non-null     int64
 4   url           50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [24]:
album_df = album_df.drop_duplicates(subset = ['album_id'])

In [25]:
artist_df = pd.DataFrame.from_dict(artist_list)

In [26]:
artist_df.head()

,artist_id,artist_name,external_url
0,1wRPtKGflJrBx9BmLsSwlU,Pritam,https://api.spotify.com/v1/artists/1wRPtKGflJr...
1,2oSONSC9zQ4UonDKnLqksx,Atif Aslam,https://api.spotify.com/v1/artists/2oSONSC9zQ4...
2,4mBxoO0pAcMbAwuTcrcLMc,Alisha Chinai,https://api.spotify.com/v1/artists/4mBxoO0pAcM...
3,1wRPtKGflJrBx9BmLsSwlU,Pritam,https://api.spotify.com/v1/artists/1wRPtKGflJr...
4,5GnnSrwNCGyfAU4zuIytiS,Mohit Chauhan,https://api.spotify.com/v1/artists/5GnnSrwNCGy...

In [27]:
artist_df = artist_df.drop_duplicates(subset = 'artist_id')

In [28]:
song_df = pd.DataFrame.from_dict(song_list)

In [29]:
song_df.head()

,song_id,song_name,duration_ms,url,song_added,album_id,artist_id
0,0dLbrlAVPPjpPqnYfmJsWk,Tera Hone Laga Hoon,299827,https://open.spotify.com/track/0dLbrlAVPPjpPqn...,2023-11-18T07:56:03Z,13t8iDyl1vkhPcO3Zl29a9,1wRPtKGflJrBx9BmLsSwlU
1,5F79ZdjOwGOhUKRHx94sr1,Dooriyan,337360,https://open.spotify.com/track/5F79ZdjOwGOhUKR...,2023-11-18T07:56:26Z,2yoQE2XBnwdUyoOkoprTfT,1wRPtKGflJrBx9BmLsSwlU
2,5a11x5PUFvJEadMRqtNtTr,Piya O Re Piya,292746,https://open.spotify.com/track/5a11x5PUFvJEadM...,2023-11-18T07:57:00Z,0OhM0xKiFdqKakSWYx0hs4,1mBydYMVBECdDmMfE2sEUO
3,2vfL2OwTXZAsr2RIZF5OZF,Aahatein (unplugged),229717,https://open.spotify.com/track/2vfL2OwTXZAsr2R...,2023-11-18T14:17:26Z,5rxVfBCI8RvZzTmnLyXQ97,64j5rJTsD25fTAcOiZWAiY
4,2QophXhN2Ls2URfoPmiviC,Kho Gaye,197763,https://open.spotify.com/track/2QophXhN2Ls2URf...,2023-11-18T14:17:39Z,0bPV8j4jfsKeoW5P3YQInX,1FWl7I9wJpb7Bhhutef4Xe

In [30]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47 entries, 0 to 48
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      47 non-null     object
 1   album_name    47 non-null     object
 2   release_date  47 non-null     object
 3   total_tracks  47 non-null     int64
 4   url           47 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.2+ KB

In [31]:
album_df['release_date'] = pd.to_datetime(album_df['release_date'])

In [32]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47 entries, 0 to 48
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      47 non-null     object
 1   album_name    47 non-null     object
 2   release_date  47 non-null     datetime64[ns]
 3   total_tracks  47 non-null     int64
 4   url           47 non-null     object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 2.2+ KB

In [33]:
song_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      50 non-null     object
 1   song_name    50 non-null     object
 2   duration_ms  50 non-null     int64
 3   url          50 non-null     object
 4   song_added   50 non-null     object
 5   album_id     50 non-null     object
 6   artist_id    50 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.9+ KB

In [34]:
song_df['song_added'] = pd.to_datetime(song_df['song_added'])

In [35]:
song_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      50 non-null     object
 1   song_name    50 non-null     object
 2   duration_ms  50 non-null     int64
 3   url          50 non-null     object
 4   song_added   50 non-null     datetime64[ns, UTC]
 5   album_id     50 non-null     object
 6   artist_id    50 non-null     object
dtypes: datetime64[ns, UTC](1), int64(1), object(5)
memory usage: 2.9+ KB